package beraber;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import beraber.Activity;
import beraber.User;

import beraber.ActivityDao;
import beraber.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig activityDaoConfig;
    private final DaoConfig userDaoConfig;

    private final ActivityDao activityDao;
    private final UserDao userDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        activityDaoConfig = daoConfigMap.get(ActivityDao.class).clone();
        activityDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        activityDao = new ActivityDao(activityDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Activity.class, activityDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        activityDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
    }

    public ActivityDao getActivityDao() {
        return activityDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
